services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092


  control-center:
    image: confluentinc/cp-enterprise-control-center:7.0.1
    hostname: control-center
    container_name: control-center-load
    depends_on:
      - kafka
      - schema-registry
    ports:
      - '9021:9021'
    environment:
      # CONTROL_CENTER_BOOTSTRAP_SERVERS: 'localhost:29092'
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  kowl:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      - kafka
      - schema-registry
    container_name: kowl
    environment:
      KAFKA_BROKERS: kafka:9092
      ALLOW_TOPIC_CREATE: true
      KAFKA_SCHEMAREGISTRY_ENABLED: true
      KAFKA_SCHEMAREGISTRY_URLS: 'http://schema-registry:8081'
    ports:
      - "8080:8080"



# services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # kafka:
  #   image: confluentinc/cp-kafka:7.0.1
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"

  #   broker:
  #     image: confluentinc/cp-server:7.7.1
  #     hostname: broker
  #     depends_on:
  #       - zookeeper
  #     ports:
  #       - '29092:29092'
  #       - '9092:9092'
  #     environment:
  #       KAFKA_BROKER_ID: 1
  #       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
  #       KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  #       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #       CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
  #       CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  #       CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  #       CONFLUENT_METRICS_ENABLE: 'true'
  #       CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.0.1
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     # SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  #   depends_on:
  #     - zookeeper
    
  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:7.7.1
  #   hostname: control-center
  #   container_name: control-center-load
  #   depends_on:
  #     - broker
  #     - schema-registry
  #   ports:
  #     - '9021:9021'
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
  #     CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
  #     PORT: 9021

  # kowl:
  #   image: quay.io/cloudhut/kowl:master
  #   depends_on:
  #     - broker
  #     - schema-registry
  #   container_name: kowl
  #   environment:
  #     KAFKA_BROKERS: broker:29092
  #     KAFKA_SASL_ENABLED: false
  #     KAFKA_SASL_USERNAME: null
  #     KAFKA_SASL_PASSWORD: null
  #     KAFKA_SCHEMAREGISTRY_ENABLED: true
  #     ALLOW_TOPIC_CREATE: true # Allow creating topics from the Kowl UI
  #     KAFKA_SCHEMAREGISTRY_URLS: 'http://schema-registry:8081'

  # kowl:
  #   image: quay.io/cloudhut/kowl:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_BROKERS: "kafka:9092"
  #     ALLOW_TOPIC_CREATE: true
  #   depends_on:
  #     - kafka

  # kowl:
  #   image: quay.io/cloudhut/kowl:master
  #   ports:
  #     - "8080:8080" # Kowl UI accessible on http://localhost:8080
  #   depends_on:
  #     - kafka
  #     - schema-registry
  #   environment:
  #     KAFKA_BROKERS: "kafka:9092"
  #     ALLOW_TOPIC_CREATE: true # Allow creating topics from the Kowl UI
  #     KAFKA_SCHEMAREGISTRY_ENABLED: true # Enable schema registry in Kowl
  #     KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081" # URL of Schema Registry
  
